// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test_Task_CodeBridge.Models.Context;

namespace Test_Task_CodeBridge.Migrations
{
    [DbContext(typeof(DogsContext))]
    [Migration("20220114220858_rename-dog-tail-height-property")]
    partial class renamedogtailheightproperty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Test_Task_CodeBridge.Models.Dog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Tail_Height")
                        .HasColumnType("float");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d0f6d45-b5b1-4813-b9c9-a61be6193c5b"),
                            Color = "Red & amber",
                            Name = "Neo",
                            Tail_Height = 22.0,
                            Weight = 32.0
                        },
                        new
                        {
                            Id = new Guid("c89cac13-821d-44c2-a429-ac14d72c91aa"),
                            Color = "black & white",
                            Name = "Jessy",
                            Tail_Height = 7.0,
                            Weight = 14.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
