// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test_Task_CodeBridge.Models.Context;

namespace Test_Task_CodeBridge.Migrations
{
    [DbContext(typeof(DogsContext))]
    [Migration("20220113104310_context-dogs-property")]
    partial class contextdogsproperty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Test_Task_CodeBridge.Models.Dog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Tail_Length")
                        .HasColumnType("float");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("56c154db-2d1f-495f-8768-c5eaa57d83e0"),
                            Color = "Red & amber",
                            Name = "Neo",
                            Tail_Length = 22.0,
                            Weight = 32.0
                        },
                        new
                        {
                            Id = new Guid("67eeb7fa-e73c-40d9-b54a-71eca0f1a4df"),
                            Color = "black & white",
                            Name = "Jessy",
                            Tail_Length = 7.0,
                            Weight = 14.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
